bucky/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls'))
]

music/urls.py
from django.conf.urls import url
from . import views

app_name ='music'
urlpatterns = [
    #/homepage
    url(r'^$', views.index, name='index'),
    #/music/1/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail,name='detail'),
    #/music/1/
    url(r'^(?P<album_id>[0-9]+)/favourite$', views.favourite,name='favourite')

]

music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=250)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=250)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title +' - '+self.file_type

music/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404
from .models import Album,Song
from django.template import loader


def index(request):
    all_albums = Album.objects.all()
    template = loader.get_template("music/index.html")
    context = {
        'all_album':all_albums,
    }
    return HttpResponse(template.render(context,request))


def detail(reuest,album_id):
    album = get_object_or_404(Album, pk=album_id)
    context ={
        'album': album,
    }
    template = loader.get_template("music/detail.html")
    return HttpResponse(template.render(context,reuest))


def favourite(request,album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError,Song.DoesNotExist):
        return render(request,"music/detail.html",{
             'album': album,
              'error_message':"you did't selected any Songs"

        })
    else:
        if selected_song.is_favourite is False:
            selected_song.is_favourite = True
        else:
            selected_song.is_favourite = False
        selected_song.save()
        return render(request,"music/detail.html",{"album": album})

templates/music/detail.html
<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>


        a{
            list-style-type: none;
        }
        li{
            list-style-type: none;
            padding-top: 3px;
        }
        .mx-auto{
            padding-top: 20px;
        }
        .container{
            padding-top: 10px;
            background-image: inherit;
        }
        .img-circle{
            height: 300px;
            width: 300px;
        }
    </style>
    <meta charset="UTF-8">

    <title>Document</title>
</head>
<body>
    <div class="container">
    
        <img class="img-circle" src="{{ album.album_logo }}" alt="">
        <h1>{{ album.album_title }}</h1>
        <h3>{{ album.artist }}</h3>
       {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
       {% endif %}
        <form action="{% url 'music:favourite' album.id %}" method="post">
             {% csrf_token %}
             {% for song in album.song_set.all %}
                    <input type="radio" id ="song{{ forloop.counter }}" name="song" value="{{ song.id }}" id="">
                    <label for="song{{ forloop.counter }}">
                        {{ song.song_title }}
                        {% if song.is_favourite %}
                            <span class="fa fa-star"></span>
                        {% endif %}
                    </label><br>
             {% endfor %}
            <input type="submit",value="Favourite" >
        </form>
        <script>

        </script>
    
    
    
    
    
    
    
    
    
    
    
    
    </div>
<script
  src="https://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>
</body>
</html>

templates/music/index.html
<!DOCTYPE html>
<html lang="en">
<head>


    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <style>

        a{
            list-style-type: none;
        }
        li{
            list-style-type: none;
            padding-top: 3px;

        }
        .mx-auto{
            padding-top: 20px;
        }
    </style>
</head>

<body>
    <div class="container mx-auto">
    <h1>Albums</h1>
         {% if all_album %}
             <ul class="list-group">
            {% for albums in all_album %}
                <li><a class ="list-group-item" href="{% url 'music:detail' albums.id %}">{{ albums.album_title }}</a></li>
            {% endfor %}
             </ul>
        {% else %}
            <h2>Sorry you dnt have any albums</h2>
        {% endif %}
    </div>

</body>
</html>